<?php
/**
 * Seamless Theme Integration
 *
 * Automatically replaces the theme's native search form with NivoSearch
 * when the "Auto-replace theme search form" setting is enabled.
 *
 * Three hooks cover all WordPress search form types:
 *
 * 1. `get_search_form` — WordPress core search form. Called by every
 *    standards-compliant classic theme, the WP_Widget_Search widget, and any
 *    template tag using get_search_form(). Covers Astra, GeneratePress,
 *    Kadence, Storefront, Blocksy, Hello Elementor, and most classic themes.
 *
 * 2. `woocommerce_product_search_form` — WooCommerce-specific product search
 *    form. Applied inside get_product_search_form(), used by the WC Product
 *    Search widget, the [woocommerce_product_search] shortcode, and WooCommerce
 *    themes (Flatsome, WoodMart, XStore, Electro, OceanWP WC mode) that call
 *    get_product_search_form() directly. This form has class
 *    "woocommerce-product-search" and is NOT caught by hook #1.
 *
 * 3. `render_block_core/search` — Block/FSE themes (Twenty Twenty-Four,
 *    Twenty Twenty-Five). These themes never call get_search_form(); their
 *    search UI is a core/search Gutenberg block whose HTML is generated by
 *    the block's own render_callback. This hook intercepts that output.
 *
 * @package NivoSearch
 * @since   2.3.0
 */

namespace NivoSearch;

defined( 'ABSPATH' ) || exit;

/**
 * Theme_Integration class.
 *
 * Hooks into get_search_form (classic themes) and render_block_core/search
 * (block/FSE themes) to swap the default search with a NivoSearch form.
 *
 * @since 2.0.2
 */
class Theme_Integration {

	/**
	 * Constructor — registers hooks only when auto-replace is enabled.
	 *
	 * @since 2.0.2
	 */
	public function __construct() {
		// Skip entirely during AJAX requests — no forms are rendered during AJAX.
		// Covers both WP AJAX (admin-ajax.php) and WC AJAX (?wc-ajax=).
		if ( ( defined( 'DOING_AJAX' ) && DOING_AJAX ) || ! empty( $_GET['wc-ajax'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return;
		}

		// Auto-replace is opt-in. Default is off.
		if ( 'yes' !== get_option( 'nivo_search_auto_replace', 'no' ) ) {
			return;
		}

		// Classic themes: intercept get_search_form() calls.
		add_filter( 'get_search_form', array( $this, 'replace_search_form' ), 99 );

		// WooCommerce product search form — filter path:
		// Catches themes/widgets that go through wc_get_product_search_form().
		add_filter( 'woocommerce_product_search_form', array( $this, 'replace_wc_product_search_form' ), 99 );

		// WooCommerce product search form — template path:
		// Catches themes that call wc_get_template('product-searchform.php')
		// directly, bypassing wc_get_product_search_form() and its filter.
		// We buffer the template output and swap it for NivoSearch HTML.
		add_action( 'woocommerce_before_template_part', array( $this, 'start_searchform_buffer' ), 10, 1 );
		add_action( 'woocommerce_after_template_part',  array( $this, 'end_searchform_buffer' ),   10, 1 );

		// Block / FSE themes (Twenty Twenty-Four, Twenty Twenty-Five, etc.):
		// intercept the rendered output of the core/search Gutenberg block.
		// Block themes build the search form HTML inside the block's render
		// callback and never call get_search_form(), so we must hook here too.
		add_filter( 'render_block_core/search', array( $this, 'replace_search_block' ), 10, 2 );
	}

	/**
	 * Return a NivoSearch form instead of the theme's classic search form.
	 *
	 * Triggered by get_search_form() — classic themes, search widgets, and
	 * template tags all funnel through this WordPress hook.
	 *
	 * @since 2.0.2
	 * @param string $form The original search form HTML generated by the theme.
	 * @return string NivoSearch AJAX search form HTML, or $form as fallback.
	 */
	public function replace_search_form( $form ) {
		if ( is_admin() ) {
			return $form;
		}

		$output = $this->get_nivo_search_html();

		return '' !== $output ? $output : $form;
	}

	/**
	 * Return a NivoSearch form instead of the WooCommerce product search form.
	 *
	 * Triggered by the `woocommerce_product_search_form` filter, which WooCommerce
	 * applies inside get_product_search_form(). This covers:
	 *   - WC_Widget_Product_Search widget
	 *   - [woocommerce_product_search] shortcode
	 *   - Any theme calling get_product_search_form() directly (Flatsome, WoodMart,
	 *     XStore, Electro, OceanWP WC mode, and most WooCommerce-specific themes)
	 *
	 * The native WC form has class "woocommerce-product-search" and is NOT
	 * intercepted by the get_search_form hook above.
	 *
	 * @since 2.0.2
	 * @param string $form The WooCommerce product search form HTML.
	 * @return string NivoSearch AJAX search form HTML, or $form as fallback.
	 */
	public function replace_wc_product_search_form( $form ) {
		if ( is_admin() ) {
			return $form;
		}

		$output = $this->get_nivo_search_html();

		return '' !== $output ? $output : $form;
	}

	/**
	 * Start output buffering before WooCommerce renders product-searchform.php.
	 *
	 * Some themes (e.g. Ecommerce Marketplace, Botiga, Shopkeeper) call
	 * wc_get_template('product-searchform.php') directly rather than going through
	 * wc_get_product_search_form(). That path never applies the
	 * woocommerce_product_search_form filter, so we intercept at template level
	 * instead by discarding the buffered WC output and printing NivoSearch HTML.
	 *
	 * @since 2.0.2
	 * @param string $template_name WooCommerce template name (relative path).
	 * @return void
	 */
	public function start_searchform_buffer( $template_name ) {
		if ( 'product-searchform.php' === $template_name ) {
			ob_start();
		}
	}

	/**
	 * End the output buffer and replace WC search form with NivoSearch.
	 *
	 * @since 2.0.2
	 * @param string $template_name WooCommerce template name (relative path).
	 * @return void
	 */
	public function end_searchform_buffer( $template_name ) {
		if ( 'product-searchform.php' !== $template_name ) {
			return;
		}

		// Discard the WooCommerce form output.
		ob_end_clean();

		// Print NivoSearch instead.
		// Note: do NOT call wc_get_template() as a fallback here — that would
		// trigger start_searchform_buffer again and create an infinite loop.
		$output = $this->get_nivo_search_html();
		if ( '' !== $output ) {
			echo $output; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		}
	}

	/**
	 * Return a NivoSearch form instead of the core/search block output.
	 *
	 * Triggered by the `render_block_core/search` filter which fires after
	 * WordPress renders every instance of the Search block placed on a page,
	 * in a template, or in the Site Editor. This covers block themes (FSE)
	 * where get_search_form() is never called.
	 *
	 * @since 2.0.2
	 * @param string $block_content Rendered HTML of the core/search block.
	 * @param array  $block         Block data array (name, attributes, etc.).
	 * @return string NivoSearch AJAX search form HTML, or $block_content as fallback.
	 */
	public function replace_search_block( $block_content, $block ) {
		// Skip inside the block editor / admin (REST block preview requests).
		if ( is_admin() ) {
			return $block_content;
		}

		// REST API block preview calls arrive with the admin-ajax.php context
		// already excluded above, but double-check for the block renderer REST route.
		if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
			return $block_content;
		}

		$output = $this->get_nivo_search_html();

		return '' !== $output ? $output : $block_content;
	}

	/**
	 * Build and return the NivoSearch shortcode HTML.
	 *
	 * Shared by both replace_search_form() and replace_search_block() so the
	 * rendering logic lives in one place.
	 *
	 * Preset resolution priority:
	 *   1. `nivo_search_theme_preset_id` option — explicitly chosen by the store
	 *      owner in Settings → Integrations → "Preset to use for theme search form".
	 *   2. `nivo_search_default_preset_created` — the auto-created default preset
	 *      (used when no explicit choice has been made).
	 *   3. No preset ID — renders a generic form (fresh installs only).
	 *
	 * @since 2.0.2
	 * @return string NivoSearch HTML, or '' if rendering failed.
	 */
	private function get_nivo_search_html() {
		// 1. Explicitly chosen preset.
		$chosen_preset_id = (int) get_option( 'nivo_search_theme_preset_id', 0 );

		// 2. Fall back to the store's default preset.
		if ( ! $chosen_preset_id ) {
			$chosen_preset_id = (int) get_option( 'nivo_search_default_preset_created', 0 );
		}

		// Validate the preset still exists (it may have been deleted).
		if ( $chosen_preset_id ) {
			$post = get_post( $chosen_preset_id );
			if ( ! $post || 'nivo_search_preset' !== $post->post_type || 'publish' !== $post->post_status ) {
				$chosen_preset_id = 0;
			}
		}

		$shortcode_atts = $chosen_preset_id ? 'id="' . $chosen_preset_id . '"' : '';
		$output         = do_shortcode( '[nivo_search ' . $shortcode_atts . ']' );

		return trim( $output );
	}
}
