<?php
/**
 * Seamless Theme Integration
 *
 * Automatically replaces the theme's native search form with NivoSearch
 * when the "Auto-replace theme search form" setting is enabled.
 *
 * Classic themes: hooks `get_search_form` — called by every standards-compliant
 * theme, widget, and template tag. Covers Astra, OceanWP, GeneratePress,
 * Kadence, Storefront, Blocksy, Hello, Flatsome, and any theme that uses
 * get_search_form() or the WP_Widget_Search widget.
 *
 * Block themes (FSE): hooks `render_block_core/search` — the filter WordPress
 * fires after rendering the core/search Gutenberg block. Block themes such as
 * Twenty Twenty-Four and Twenty Twenty-Five never call get_search_form();
 * their search UI is a block whose HTML is generated by the block's own
 * render_callback. This second hook ensures NivoSearch works with those themes
 * too, including the default Search block placed on any page or template.
 *
 * @package NivoSearch
 * @since   2.3.0
 */

namespace NivoSearch;

defined( 'ABSPATH' ) || exit;

/**
 * Theme_Integration class.
 *
 * Hooks into get_search_form (classic themes) and render_block_core/search
 * (block/FSE themes) to swap the default search with a NivoSearch form.
 *
 * @since 2.0.2
 */
class Theme_Integration {

	/**
	 * Constructor — registers hooks only when auto-replace is enabled.
	 *
	 * @since 2.0.2
	 */
	public function __construct() {
		// Skip entirely during AJAX requests — no forms are rendered during AJAX.
		// Covers both WP AJAX (admin-ajax.php) and WC AJAX (?wc-ajax=).
		if ( ( defined( 'DOING_AJAX' ) && DOING_AJAX ) || ! empty( $_GET['wc-ajax'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return;
		}

		// Default to 'no' — auto-replacing theme forms is opt-in.
		if ( 'yes' !== get_option( 'nivo_search_auto_replace', 'no' ) ) {
			return;
		}

		// Classic themes: intercept get_search_form() calls.
		add_filter( 'get_search_form', array( $this, 'replace_search_form' ), 99 );

		// Block / FSE themes (Twenty Twenty-Four, Twenty Twenty-Five, etc.):
		// intercept the rendered output of the core/search Gutenberg block.
		// Block themes build the search form HTML inside the block's render
		// callback and never call get_search_form(), so we must hook here too.
		add_filter( 'render_block_core/search', array( $this, 'replace_search_block' ), 10, 2 );
	}

	/**
	 * Return a NivoSearch form instead of the theme's classic search form.
	 *
	 * Triggered by get_search_form() — classic themes, search widgets, and
	 * template tags all funnel through this WordPress hook.
	 *
	 * @since 2.0.2
	 * @param string $form The original search form HTML generated by the theme.
	 * @return string NivoSearch AJAX search form HTML, or $form as fallback.
	 */
	public function replace_search_form( $form ) {
		if ( is_admin() ) {
			return $form;
		}

		$output = $this->get_nivo_search_html();

		return '' !== $output ? $output : $form;
	}

	/**
	 * Return a NivoSearch form instead of the core/search block output.
	 *
	 * Triggered by the `render_block_core/search` filter which fires after
	 * WordPress renders every instance of the Search block placed on a page,
	 * in a template, or in the Site Editor. This covers block themes (FSE)
	 * where get_search_form() is never called.
	 *
	 * @since 2.0.2
	 * @param string $block_content Rendered HTML of the core/search block.
	 * @param array  $block         Block data array (name, attributes, etc.).
	 * @return string NivoSearch AJAX search form HTML, or $block_content as fallback.
	 */
	public function replace_search_block( $block_content, $block ) {
		// Skip inside the block editor / admin (REST block preview requests).
		if ( is_admin() ) {
			return $block_content;
		}

		// REST API block preview calls arrive with the admin-ajax.php context
		// already excluded above, but double-check for the block renderer REST route.
		if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
			return $block_content;
		}

		$output = $this->get_nivo_search_html();

		return '' !== $output ? $output : $block_content;
	}

	/**
	 * Build and return the NivoSearch shortcode HTML.
	 *
	 * Shared by both replace_search_form() and replace_search_block() so the
	 * rendering logic lives in one place.
	 *
	 * Preset resolution priority:
	 *   1. `nivo_search_theme_preset_id` option — explicitly chosen by the store
	 *      owner in Settings → Integrations → "Preset to use for theme search form".
	 *   2. `nivo_search_default_preset_created` — the auto-created default preset
	 *      (used when no explicit choice has been made).
	 *   3. No preset ID — renders a generic form (fresh installs only).
	 *
	 * @since 2.0.2
	 * @return string NivoSearch HTML, or '' if rendering failed.
	 */
	private function get_nivo_search_html() {
		// 1. Explicitly chosen preset.
		$chosen_preset_id = (int) get_option( 'nivo_search_theme_preset_id', 0 );

		// 2. Fall back to the store's default preset.
		if ( ! $chosen_preset_id ) {
			$chosen_preset_id = (int) get_option( 'nivo_search_default_preset_created', 0 );
		}

		// Validate the preset still exists (it may have been deleted).
		if ( $chosen_preset_id ) {
			$post = get_post( $chosen_preset_id );
			if ( ! $post || 'nivo_search_preset' !== $post->post_type || 'publish' !== $post->post_status ) {
				$chosen_preset_id = 0;
			}
		}

		$shortcode_atts = $chosen_preset_id ? 'id="' . $chosen_preset_id . '"' : '';
		$output         = do_shortcode( '[nivo_search ' . $shortcode_atts . ']' );

		return trim( $output );
	}
}
